v1.7.4

diff --git a/scripts/test_eeyore b/scripts/test_eeyore
--- a/scripts/test_eeyore
+++ b/scripts/test_eeyore
@@ -12,10 +12,10 @@ SID=$RANDOM
 
 checkRun(){
 	$*
-	errCode=$?
-	if [ $errCode != 0 ]
+	errCodeRun=$?
+	if [ $errCodeRun != 0 ]
 	then 
-		echo "[`date`][SID] Error occurred while executing command line: \"$*\". Returned with error code ($errCode)"
+		echo "[`date`][SID] Error occurred while executing command line: \"$*\". Returned with error code ($errCodeRun)"
 		exit
 	fi
 }
@@ -115,14 +115,13 @@ checkLab(){
 		do
 			testName=(`basename $file | sed 's/\./ /g'`)
 			checkRun cp $file $ftpTemp/test_$SID.c
-			#if [ -f $tempDir/compile_eeyore_*.log ]
-			#then checkRun rm $tempDir/compile_eeyore_*.log
-			#fi
+			checkRun rm -f ./compile_eeyore_*.log
+			checkRun rm -f ./simulate_eeyore.log
 
 			# Use eeyore compile C file
 			echo -e "cd $eeyoreDir\n./eeyore < $ftpTemp/test_$SID.c" | timeout $timeOut su - $userName  > $ftpTemp/test_$SID.e 2> $tempDir/compile_eeyore_c2e.log
 			errCode=$?
-			checkRun cp $tempDir/compile_eeyore_c2e.log ./compile_eeyore_runtime.log
+			checkRun cp $tempDir/compile_eeyore_c2e.log $tempDir/compile_eeyore_runtime.log
 			if [ $errCode = 124 ]
 			then 
 				mailFormat=RUN_TIMEOUT
diff --git a/scripts/test_riscv32 b/scripts/test_riscv32
--- a/scripts/test_riscv32
+++ b/scripts/test_riscv32
@@ -13,10 +13,10 @@ SID=$RANDOM
 
 checkRun(){
 	$*
-	errCode=$?
-	if [ $errCode != 0 ]
+	errCodeRun=$?
+	if [ $errCodeRun != 0 ]
 	then 
-		echo "[`date`][SID] Error occurred while executing command line: \"$*\". Returned with error code ($errCode)"
+		echo "[`date`][SID] Error occurred while executing command line: \"$*\". Returned with error code ($errCodeRun)"
 		exit
 	fi
 }
@@ -116,16 +116,15 @@ checkLab(){
 		do
 			testName=(`basename $file | sed 's/\./ /g'`)
 			checkRun cp $file $ftpTemp/test_$SID.c
-			#if [ -f $tempDir/compile_riscv32_*.log ]
-			#then checkRun rm $tempDir/compile_riscv32_*.log
-			#fi
+			checkRun rm -f ./compile_riscv32_*.log
+			checkRun rm -f ./simulate_riscv32.log
 			
 			if [ -f ./riscv32C ]
 			then
 				# Use riscv32C compile C file
 				echo -e "cd $riscv32Dir\n./riscv32C < $ftpTemp/test_$SID.c" | timeout $timeOut su - $userName  > $ftpTemp/test_$SID.s 2> $tempDir/compile_riscv32_c2s.log
 				errCode=$?
-				checkRun cp $tempDir/compile_riscv32_c2s.log ./compile_riscv32_runtime.log
+				checkRun cp $tempDir/compile_riscv32_c2s.log $tempDir/compile_riscv32_runtime.log
 				if [ $errCode = 124 ]
 				then 
 					mailFormat=RUN_TIMEOUT
@@ -148,7 +147,7 @@ checkLab(){
 				# Use eeyore compile C file
 				echo -e "cd $riscv32Dir\n./eeyore < $ftpTemp/test_$SID.c" | timeout $timeOut su - $userName  > $ftpTemp/test_$SID.e 2> $tempDir/compile_riscv32_c2e.log
 				errCode=$?
-				checkRun cp $tempDir/compile_riscv32_c2e.log ./compile_riscv32_runtime.log
+				checkRun cp $tempDir/compile_riscv32_c2e.log $tempDir/compile_riscv32_runtime.log
 				if [ $errCode = 124 ]
 				then 
 					mailFormat=RUN_TIMEOUT
@@ -171,7 +170,7 @@ checkLab(){
 				# Use tigger compile eeyore file
 				echo -e "cd $riscv32Dir\n./tigger < $ftpTemp/test_$SID.e" | timeout $timeOut su - $userName  > $ftpTemp/test_$SID.t 2> $tempDir/compile_riscv32_e2t.log
 				errCode=$?
-				checkRun cp $tempDir/compile_riscv32_e2t.log ./compile_riscv32_runtime.log
+				checkRun cp $tempDir/compile_riscv32_e2t.log $tempDir/compile_riscv32_runtime.log
 				if [ $errCode = 124 ]
 				then 
 					mailFormat=RUN_TIMEOUT
@@ -194,7 +193,7 @@ checkLab(){
 				# Use riscv32 compile tigger file
 				echo -e "cd $riscv32Dir\n./riscv32 < $ftpTemp/test_$SID.t" | timeout $timeOut su - $userName  > $ftpTemp/test_$SID.s 2> $tempDir/compile_riscv32_t2s.log
 				errCode=$?
-				checkRun cp $tempDir/compile_riscv32_t2s.log ./compile_riscv32_runtime.log
+				checkRun cp $tempDir/compile_riscv32_t2s.log $tempDir/compile_riscv32_runtime.log
 				if [ $errCode = 124 ]
 				then 
 					mailFormat=RUN_TIMEOUT
@@ -219,7 +218,7 @@ checkLab(){
 			# Compiling assemble language to machine language
 			timeout $timeOut $riscvPath/riscv32-unknown-linux-gnu-gcc $ftpTemp/test_$SID.s $installPath/lib/lib32.s -static -o $tempDir/${testName}_$SID > $tempDir/compile_riscv32_s2o.log 2>&1
 			errCode=$?
-			checkRun cp $tempDir/compile_riscv32_s2o.log ./compile_riscv32_runtime.log
+			checkRun cp $tempDir/compile_riscv32_s2o.log $tempDir/compile_riscv32_runtime.log
 			if [ $errCode = 124 ]
 			then 
 				mailFormat=COMPILE_ASSEMBLE_TIMEOUT
diff --git a/scripts/test_tigger b/scripts/test_tigger
--- a/scripts/test_tigger
+++ b/scripts/test_tigger
@@ -12,10 +12,10 @@ SID=$RANDOM
 
 checkRun(){
 	$*
-	errCode=$?
-	if [ $errCode != 0 ]
+	errCodeRun=$?
+	if [ $errCodeRun != 0 ]
 	then 
-		echo "[`date`][SID] Error occurred while executing command line: \"$*\". Returned with error code ($errCode)"
+		echo "[`date`][SID] Error occurred while executing command line: \"$*\". Returned with error code ($errCodeRun)"
 		exit
 	fi
 }
@@ -116,16 +116,15 @@ checkLab(){
 		do
 			testName=(`basename $file | sed 's/\./ /g'`)
 			checkRun cp $file $ftpTemp/test_$SID.c
-			#if [ -f $tempDir/compile_tigger_*.log ]
-			#then checkRun rm $tempDir/compile_tigger_*.log
-			#fi		
+			checkRun rm -f ./compile_tigger_*.log
+			checkRun rm -f ./simulate_tigger.log		
 			
 			if [ -f ./tiggerC ]
 			then
 				# Use tiggerC compile C file
 				echo -e "cd $tiggerDir\n./tiggerC < $ftpTemp/test_$SID.c" | timeout $timeOut su - $userName  > $ftpTemp/test_$SID.t 2> $tempDir/compile_tigger_c2t.log
 				errCode=$?
-				checkRun cp $tempDir/compile_tigger_c2t.log ./compile_tigger_runtime.log
+				checkRun cp $tempDir/compile_tigger_c2t.log $tempDir/compile_tigger_runtime.log
 				if [ $errCode = 124 ]
 				then 
 					mailFormat=RUN_TIMEOUT
@@ -148,7 +147,7 @@ checkLab(){
 				# Use eeyore compile C file
 				echo -e "cd $tiggerDir\n./eeyore < $ftpTemp/test_$SID.c" | timeout $timeOut su - $userName  > $ftpTemp/test_$SID.e 2> $tempDir/compile_tigger_c2e.log
 				errCode=$?
-				checkRun cp $tempDir/compile_tigger_c2e.log ./compile_tigger_runtime.log
+				checkRun cp $tempDir/compile_tigger_c2e.log $tempDir/compile_tigger_runtime.log
 				if [ $errCode = 124 ]
 				then 
 					mailFormat=RUN_TIMEOUT
@@ -171,7 +170,7 @@ checkLab(){
 				# Use tigger compile eeyore file
 				echo -e "cd $tiggerDir\n./tigger < $ftpTemp/test_$SID.e" | timeout $timeOut su - $userName  > $ftpTemp/test_$SID.t 2> $tempDir/compile_tigger_e2t.log
 				errCode=$?
-				checkRun cp $tempDir/compile_tigger_e2t.log ./compile_tigger_runtime.log
+				checkRun cp $tempDir/compile_tigger_e2t.log $tempDir/compile_tigger_runtime.log
 				if [ $errCode = 124 ]
 				then 
 					mailFormat=RUN_TIMEOUT
